### ISSUE TITLE
License is showing as UNKNOWN in pip show.

### ISSUE THREAD

**Issue by sureshvigneshbe** [takluyver/backcall#8]
Backcall 0.2.0 license is showing in PIP show as UNKNOWN.

**Comment by takluyver** [comment]
I usually release all my projects with the license in a classifier (`License :: OSI Approved :: BSD License`) rather than the free-text license field. PyPI is [smart enough](https://pypi.org/project/backcall/) to use this for the license info it shows.

[PEP 639](https://www.python.org/dev/peps/pep-0639/) is meant to provide a more carefully standardised way of describing licenses. Once that's accepted, I'll be happy to use it.

**Comment by sureshvigneshbe** [comment]
Thank you for the clarification !!!.
